name: bangers
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# --------------- PACKAGES --------------- #

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  firebase_auth: ^5.3.3
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.5.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  
  uses-material-design: true

  assets:
  - assets/fonts
  - assets/images
  - assets/icons

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
        - weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - weight: 800
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - weight: 200
        - asset: assets/fonts/Poppins-Italic.ttf
        - weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
        - weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
        - weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
        - weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - weight: 600
        - asset: assets/fonts/Poppins-Thin.ttf
        - weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
        - weight: 100
